--------------------------------------------------------
--  파일이 생성됨 - 목요일-10월-20-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table GROUP_RELATION
--------------------------------------------------------

  CREATE TABLE "HR"."GROUP_RELATION" 
   (	"MED_GROUP" VARCHAR2(26 BYTE), 
	"FOOD_NAME" VARCHAR2(26 BYTE), 
	"GROUP_RELATION" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.GROUP_RELATION
SET DEFINE OFF;
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','솔잎','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','칡','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','결명자','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','메밀','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','라면','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','소주','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','맥주','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','와인','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','막걸리','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('혈압강하제','튀김','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','양배추','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','호두','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','마늘','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','타히보','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','매실 액기스','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','물엿','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','초콜릿','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','잼','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('당뇨병용제','아이스크림','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','오미자','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','은행','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','도라지','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','배','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','더덕','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','튀김','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','우유','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','땅콩','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('진해거담제','복숭아','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','흰민들레','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','마','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','양배추','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','브로커리','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','부추','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','감자','GOOD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','소주','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','맥주','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','와인','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','막걸리','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','커피','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','밀가루','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','사이다','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','콜라','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','웰치스','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','환타','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','우유','BAD');
Insert into HR.GROUP_RELATION (MED_GROUP,FOOD_NAME,GROUP_RELATION) values ('소화성궤양용제','레몬','BAD');
--------------------------------------------------------
--  DDL for Index SYS_C007483
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SYS_C007483" ON "HR"."GROUP_RELATION" ("MED_GROUP", "FOOD_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GROUP_RELATION
--------------------------------------------------------

  ALTER TABLE "HR"."GROUP_RELATION" MODIFY ("GROUP_RELATION" NOT NULL ENABLE);
  ALTER TABLE "HR"."GROUP_RELATION" ADD PRIMARY KEY ("MED_GROUP", "FOOD_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
