--------------------------------------------------------
--  파일이 생성됨 - 화요일-10월-18-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INGREDIENT_RELATION
--------------------------------------------------------

  CREATE TABLE "HR"."INGREDIENT_RELATION" 
   (	"MED_MAIN_INGREDIENT" VARCHAR2(40 BYTE), 
	"FOOD_INGREDIENT" VARCHAR2(35 BYTE), 
	"INGREDIENT_RELATION" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.INGREDIENT_RELATION
SET DEFINE OFF;
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('글리메피리드','탄수화물','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('글리메피리드','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('글리메피리드','식이섬유','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜 디씨','우유','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜 디씨','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜 디씨','알리신','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('덱시부프로펜 디씨','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디멘히드리네이트','전해질','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디멘히드리네이트','수분','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디멘히드리네이트','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디아제팜','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디아제팜','니코틴','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디아제팜','자몽주스','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디아제팜','천연진정제','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('디히드로코데인타르타르산염','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','물','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','마그네슘','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','비타민 B','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','비타민B','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('라니티딘염산염','철분','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('레보세티리진염산염','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('레보플록사신','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('레보플록사신','아연','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('레보플록사신','철분','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('레보플록사신','마그네슘','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('레보플록사신','칼슘','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('록소프로펜나트륨수화물','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('록소프로펜나트륨수화물','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('메트포르민염산염','탄수화물','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('메트포르민염산염','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('메트포르민염산염','비타민 B','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('무수아토르바스타틴칼슘','자몽','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('무수아토르바스타틴칼슘','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('무수아토르바스타틴칼슘','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('무수아토르바스타틴칼슘','자몽주스','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('브롬화수소산페노테롤','감초뿌리','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('브롬화수소산페노테롤','마황','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('브롬화수소산페노테롤','인삼','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('세티리진염산염','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('수산화마그네슘','철분','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('수산화마그네슘','비타민 C','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('슈도에페드린염산염','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('시메티딘','마그네슘','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('시메티딘','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('시메티딘','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('시메티딘','비타민 B','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('시프로플록사신','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('시프로플록사신','무기질','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아세트아미노펜','식이섬유','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아세트아미노펜','비타민C','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아세트아미노펜','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아세트아미노펜','에키나시아','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아세트아미노펜','우유','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','철분','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','비타민E','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','비타민A','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','녹차','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('아스피린','우유','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('알프라졸람','니코틴','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('알프라졸람','진정제성분','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('알프라졸람','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('알프라졸람','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('이부프로펜','카페인','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('이부프로펜','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('클라불란산칼륨','고지방','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('클래리트로마이신','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('클래리트로마이신','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('클로르페니라민말레산염','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('클로르페니라민말레산염','수분','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('클로르페니라민말레산염','전해질','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드로클로로티아지드','칼륨','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드로클로로티아지드','알코올','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드로클로로티아지드','우유','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드로클로로티아지드','칼륨','GOOD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드로클로로티아지드','비타민D','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드로클로로티아지드','칼슘','BAD');
Insert into HR.INGREDIENT_RELATION (MED_MAIN_INGREDIENT,FOOD_INGREDIENT,INGREDIENT_RELATION) values ('히드록시진염산염','알코올','BAD');
