DROP TABLE search_log;

CREATE TABLE search_log(
		SERIAL_NUM                        		NUMBER(4)    	PRIMARY KEY,
		USERID                          		VARCHAR2(15)	NOT NULL,
		MED_KEY    	                    		VARCHAR2(50)	NOT NULL,
		FOOD_KEY                         		VARCHAR2(50)	NOT NULL,
		SEARCH_DATE                       		VARCHAR2(20)	NOT NULL
);


INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (1, 'chan', '타이레놀', '커피', '2016/09/04');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (2, 'HYJ', '아스피린', '사과', '2016/09/05');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (3, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (4, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (5, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (6, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (7, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (8, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (9, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (10, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (11, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (12, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (13, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (14, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (15, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (16, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (17, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (18, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (19, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (20, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (21, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (22, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (23, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (24, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (25, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (26, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (27, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (28, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (29, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (30, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (31, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (32, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (33, '', '', '', '2016//');

INSERT INTO search_log (SERIAL_NUM, USERID, MED_KEY, FOOD_KEY, SEARCH_DATE)
VALUES (34, '', '', '', '2016//');
--test
commit;